name: deriv_bot_mobile
description: Télécommande mobile pour le bot de trading Deriv.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
